star-swagger:
  basePackage: com.star.truffle.module
  enable: true 
starMysql:
  writeSupply:
    username: root
    password: uAiqwVwjJ8-i
    url: jdbc:mysql://47.105.38.227:3306/blyx?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    pool:
      maxActive: 30
    mybatisConfig: mapper/mybatis-config.xml
    mapperLocation: classpath*:/mapper/**/write/*.xml
    mapperScanner: com/star/truffle/module/**/dao/write
    aliasPackage: com.star.truffle.module.**.domain
 
  readSupply:
    username: root
    password: uAiqwVwjJ8-i
    url: jdbc:mysql://47.105.38.227:3306/blyx?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    pool:
      maxActive: 50
    mybatisConfig: mapper/mybatis-config.xml
    mapperLocation: classpath*:/mapper/**/read/*.xml
    mapperScanner: com/star/truffle/module/**/dao/read
    aliasPackage: com.star.truffle.module.**.domain

logging:
  file: ${spring.application.name}

starSecurity:
  ignore:
    - /index 
spring:
  redis:
    cluster.nodes:
      - 10.10.11.74:7000
      - 10.10.11.74:7001
      - 10.10.11.74:7002 
      - 10.10.11.74:7003
      - 10.10.11.74:7004
      - 10.10.11.74:7005
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
  cache:
    redis:
      time-to-live: 2592000s